### ISSUE TITLE
V2.1 problem with call dsrval

### ISSUE THREAD

**Issue by BertheGrandPied** [marceluda/rp_lock-in_pid#5]
Hello,

When loading the App v2.1 got a problem with the last modification made on the code when using from web server (commit FIX derivative labels). The App was installed using the upload script given in the zip archive `lock_in+pid-0.2.1-1-devbuild.zip` was taken from there : https://marceluda.github.io/rp_lock-in_pid/TheApp/install/.

Using debug mode of my web navigator (tried Firefox and Chromium), it looks like the function dsrval used in both lock_pidA_update and lock_pidB_update is not defined and make the app crash.

Here a copy of error message :

```
ReferenceError: dsrval is not defined lock_in+pid:1775:5
    lock_pidA_update (index):1775
    <anonyme> (index):1540
    jQuery 4
        c
        fireWith
        ready
        q
```

Am I missing something ?

Regards

L.D

**Comment by marceluda** [comment]
You are completely right. I made a mistake when fixing an old bug.

I've just fix it again and now should be working. Yo can download it again from https://marceluda.github.io/rp_lock-in_pid/TheApp/install/ . It's the same version, but I changed the HTML. I tested the bug is out.

Let me know if you still have troubles.

Regards.

marcelo

**Comment by BertheGrandPied** [comment]
Thanks a lot for this fix, that was quick ! And thanks for your work, it help a lot.

Regards

L.D
